// <auto-generated />
using System;
using DailyRugby.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyRugby.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809150938_AddedRounds")]
    partial class AddedRounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DailyRugby.Domain.Championship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Championships", (string)null);
                });

            modelBuilder.Entity("DailyRugby.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChampionshipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("DailyRugby.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CakesAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasGeneralCoach")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasInsigthCoach")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPhysiqueCoach")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTechniqueCoach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Insight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Physique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Technique")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("DailyRugby.Domain.TeamGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coach")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GetsMoraleBoostIfWins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMoraleBoost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsingCake")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tactic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamGames", (string)null);
                });

            modelBuilder.Entity("DailyRugby.Domain.Game", b =>
                {
                    b.HasOne("DailyRugby.Domain.Championship", null)
                        .WithMany("Games")
                        .HasForeignKey("ChampionshipId");

                    b.HasOne("DailyRugby.Domain.TeamGame", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyRugby.Domain.TeamGame", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("DailyRugby.Domain.Team", b =>
                {
                    b.HasOne("DailyRugby.Domain.Championship", null)
                        .WithMany("Teams")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyRugby.Domain.TeamGame", b =>
                {
                    b.HasOne("DailyRugby.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DailyRugby.Domain.Championship", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
