<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DailyRugby.Domain\DailyRugby.Domain.csproj" />
    <ProjectReference Include="..\DailyRugby.Shared\DailyRugby.Shared.csproj" />
  </ItemGroup>

</Project>
